services:
  development:
    image: todo-app:development
    build:
      context: .
      target: development
    env_file:
      - .env
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./todo_app
        target: /opt/todoapp/todo_app

  production:
    image: todo-app:production
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - "80:8000"

  runTests:
    image: todo-app:local_tests
    build:
      context: .
      target: local_tests
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./todo_app
        target: /opt/todoapp/todo_app
      - type: bind
        source: ./tests
        target: /opt/todoapp/tests
      - type: bind
        source: ./e2eTests
        target: /opt/todoapp/e2eTests

  watchUnitTests:
    image: todo-app:watch_unit_tests
    build:
      context: .
      target: watch_unit_tests
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./todo_app
        target: /opt/todoapp/todo_app
      - type: bind
        source: ./tests
        target: /opt/todoapp/tests

