services:
  development:
    image: todo-app:development
    depends_on:
      - localdb
    build:
      context: .
      target: development
    env_file:
      - .env.local
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        source: ./todo_app
        target: /opt/todoapp/todo_app

  production:
    image: todo-app:production
    build:
      context: .
      target: production
    env_file:
      - .env
    ports:
      - "80:8000"

  runTests:
    image: todo-app:local_tests
    depends_on:
      - localdb
    build:
      context: .
      target: local_tests
    env_file:
      - .env.local
    volumes:
      - type: bind
        source: ./todo_app
        target: /opt/todoapp/todo_app
      - type: bind
        source: ./tests
        target: /opt/todoapp/tests
      - type: bind
        source: ./e2eTests
        target: /opt/todoapp/e2eTests

  watchUnitTests:
    image: todo-app:watch_unit_tests
    build:
      context: .
      target: watch_unit_tests
    env_file:
      - .env
    volumes:
      - type: bind
        source: ./todo_app
        target: /opt/todoapp/todo_app
      - type: bind
        source: ./tests
        target: /opt/todoapp/tests

  localdb:
    image: mongo
    restart: always
    container_name: local_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: notarealpassword
    command: mongod --quiet --logpath /var/log/mongodb/mongod.log
    volumes:
      - "localdb:/data/db"
    ports:
      - "27017:27017"

volumes:
  localdb:

