flowchart BT
    User -->|Creates, views, completes, uncompletes and deletes ToDos| ToDoApp
    subgraph App[&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspToDo App]
        ToDoApp
    end
    subgraph External
        CosmosDB
    end
    ToDoApp -->|Creates, Retrieves, Updates, and Deletes ToDo data in database| CosmosDB
