flowchart BT
    User -->|Creates, views, completes, uncompletes and deletes ToDos via HTTPS| Gunicorn
    Gunicorn -->|Passes HTTP requests to and responses from| Flask(Flask framework)
    Flask -->|Routes requests to correct handler and returns Json/ html| ToDoApp(ToDo App logic)
    ToDoApp -->|Creates, Retrieves, Updates, and Deletes ToDo items from database| CosmosDB
    subgraph App [&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbspToDo App]
        Gunicorn
        Flask
        ToDoApp
    end
    subgraph External
        CosmosDB
    end

