name: Build on push
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target pipeline_integration_tests .
    - run: docker run todo-app:pipeline_integration_tests
    - run: docker build --target pipeline_e2e_tests .
    - run: >
        docker run 
        -e FLASK_APP=todo_app/app
        -e TRELLO_TO_DO_BOARD_ID=65cb37a378d7b6f10d62c208 
        -e TRELLO_ORGANIZATION_ID=65cb37900e446a315b3b1fbc 
        -e TRELLO_API_KEY=$TRELLO_API_KEY 
        -e TRELLO_API_TOKEN=$TRELLO_API_TOKEN
        todo-app:pipeline_e2e_tests
