name: Build on push
on: [push]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - run: docker build --target pipelineTests .
    - run: docker run --env-file ./.env todo-app:pipelineTests